name: mir-kiosk-x11-example
version: '0.1'
summary: example (glxgears) X11 kiosk, using mir_kiosk_x11
description: |
  example (glxgears) X11 kiosk, using mir_kiosk_x11
base: core20
confinement: strict
grade: devel

apps:
  mir-kiosk-x11-example:
#    daemon: simple
#    restart-condition: always
    command-chain:
      - env-setup
    command: usr/local/bin/x11_kiosk_launch glxgears

parts:
  glxgears:
    plugin: nil
    stage-packages:
      - mesa-utils

# The rest is "boiler plate" to set up an X11 environment for the application
  ppa-setup:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -y ppa:mir-team/release
      sudo apt install --assume-yes libmiral-dev
      snapcraftctl pull

  xwayland:
    plugin: nil
    build-attributes:
      - no-patchelf
    stage-packages:
      - xwayland
      - libbz2-1.0

  mir-kiosk-x11:
    after: [ppa-setup]
    plugin: cmake
    source: https://github.com/MirServer/mir_kiosk_x11.git
    build-packages:
      - pkg-config
      - libmiral-dev
      - make
      - g++
    stage-packages:
      - inotify-tools
      - libmiral4
      #      - mir-graphics-drivers-desktop
      - mir-platform-graphics-wayland18
      - dmz-cursor-theme

  env-setup:
    plugin: dump
    source: env-setup

architectures:
  - armhf
  - arm64
  - amd64

layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp

plugs:
  opengl:
  wayland:
  network-bind: # to serve X11

environment:
  # Prep for Mir
  MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
  MIR_SERVER_XWAYLAND_PATH: ${SNAP}/usr/bin/Xwayland
  # GL setup
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LD_LIBRARY_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/lib/${SNAPCRAFT_ARCH_TRIPLET}
